feat(Report): 리뷰신고목록 전체조회 메서드  및 기능 구현 시 필요한 DTO 생성 #115
ssg-240304-java2/final-whiskey pull request #116
Opened 2024-08-12 07:02 UTC by l2chmnl

- 이전 커밋도 그렇고 일단 개인 Test를 위해 Restaurant, Review, (ReviewComment)에 대한 DTO를 생성했습니다. 추후 해당 기능 당사자들과 논의 후 삭제 or 위치 변경 결정하겠습니다.

2024-08-12 11:19 UTC, kebin0591 submitted a review, later dismissed
인정합니다.

2024-08-12 11:30 UTC, speter6501 submitted a review, later dismissed
고생하셨습니다

2024-08-12 12:43 UTC, zZerorok approved these changes
확인했습니다 고생하셨어요!!

2024-08-12 12:43 UTC, zZerorok commented on src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
>      @Autowired
@RequiredArgsConstructor 어노테이션이 생성자 주입을 해주니 @Autowired는 빼도 될 것 같습니다!!

2024-08-13 00:31 UTC, DokaDev requested changes
Reviewr관련해 작업해주신 dto는
review 파트로 코로케이션된 패키지 내에 /dto 패키지 추가 생성하여 이동부탁드립니다.

2024-08-13 00:31 UTC, DokaDev commented on src/test/java/com/whiskey/rvcom/report/RestaurantReportTest.java
> +    public void findAll() {
테스트케이스의 기댓값이 명시되어있지 않아 테스트 결과의 유추가 어렵습니다.

단정문 등을 사용해서 테스트 케이스를 명확하게 명시부탁드리겠습니다.

2024-08-13 00:31 UTC, DokaDev commented on src/test/java/com/whiskey/rvcom/report/RestaurantReportTest.java
> +    public void save() {
더미데이터 입력의 케이스를 제외한 등록 로직 또한 단정문을 사용하여 기댓값으로 정상동작 여부를 유추할 수 있도록 테스트 구성 부탁드리겠습니다.

2024-08-13 00:31 UTC, DokaDev commented on src/test/java/com/whiskey/rvcom/report/ReviewCommentReportTest.java
> +        List<ReviewCommentReportDTO> reports  = reviewCommentReportService.getAllReviewCommentReports();
상기 내용과 동일합니다.

2024-08-13 00:31 UTC, DokaDev commented on src/test/java/com/whiskey/rvcom/report/ReviewReportTest.java
> +public class ReviewReportTest {
상기 내용과 동일합니다.

2024-08-13 01:33 UTC, kebin0591 approved these changes

2024-08-13 01:34 UTC, merged