검색결과 페이지에 카카오지도 렌더링 및 사용자의 현위치 표시 기능 구현
ssg-240304-java2/final-whiskey pull request #121
Opened 2024-08-12 08:54 UTC by Lucas-Choi-17

2024-08-12 09:14 UTC, kebin0591 approved these changes
리뷰 승인하겠습미다.

2024-08-12 09:14 UTC, kebin0591 commented on src/main/resources/templates/searchResults.html
> +                    <span class="location">인천시</span>
이부분도 나중에 위치따라 변경 되도록 해주세요!

2024-08-12 11:31 UTC, speter6501 submitted a review, later dismissed
수고하셧습니당

2024-08-12 12:45 UTC, zZerorok commented
고생하셨습니다~

2024-08-13 00:24 UTC, DokaDev requested changes

2024-08-13 00:24 UTC, DokaDev commented on src/main/resources/application.yml
> +  apikey: { { secrets.KAKAOMAP_API }
${{ secrets.KAKAOMAP_API }}
로 구문변경 부탁드립니다.

그리고 actions yml 수정 필요하니 업무요청 전달 부탁드리겠습니다.

2024-08-13 00:38 UTC, Lucas-Choi-17 commented on src/main/resources/application.yml
> +  apikey: { { secrets.KAKAOMAP_API }
해당부분 코드 수정완료했습니다.

2024-08-13 00:39 UTC, Lucas-Choi-17 commented
코드 수정 완료했습니다. 확인 부탁드립니다!!

2024-08-13 00:55 UTC, DokaDev approved these changes

2024-08-13 01:34 UTC, merged