ui/ux + feat(report): 식당 신고 메서드 수정
ssg-240304-java2/final-whiskey pull request #173
Opened 2024-08-14 12:10 UTC by l2chmnl

- 식당 신고 전용 -> 모든 신고 보내기

2024-08-15 02:38 UTC, kebin0591 submitted a review, later dismissed
오 작동되는걸 꼭 보고싶네요

2024-08-15 10:28 UTC, DokaDev requested changes
피드백 확인하셔서 조정해주시면 좋겠습니다.

2024-08-15 10:28 UTC, DokaDev commented on src/main/java/com/whiskey/rvcom/report/controller/CommentReportController.java
> +        reviewCommentReportDTO.setId(null);
AutoIncrement 적용된 id필드는 명시적으로 null대입하지 않는 게 어떨지 싶습니다.
다른 분들이 dto 사용 상 복잡도를 조금 키우는 영향이 있지 않을까 싶습니다.

2024-08-15 10:28 UTC, DokaDev commented on src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
> +        restaurantReportDTO.setRestaurantDTO(restaurantReportService.returnRestaurantDTO(report.getId()));
<img width="901" alt="image" src="https://github.com/user-attachments/assets/4b7aee84-3346-4c1b-8f7b-f681351dea5c">

레스토랑 객체 전달받는 부분은 restaurantService 객체를 주입받으셔서 사용하시는 게 적절해 보입니다.
동일 로직이 서로 다른 서비스 2개에서 각각 구현되는 것은 SRP원칙에 위배되며, 응집도를 저하시키는 요소입니다. 
승인님께서 제공해주신, 혹은 제공해 주실 로직을 재사용하는 내용으로 조정이 필요합니다.

2024-08-15 10:28 UTC, DokaDev commented on src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
> +        restaurantReportDTO.setRestaurantDTO(restaurantReportService.returnRestaurantDTO(report.getId()));
추가로 앞선 다른 서비스단 로직에서 객체를 받아오는 부분의 메소드명의 prefix는 대개 `get`으로 적용해 주셨는데 해당의 로직을 포함하여 일부 로직이 `return`으로 되어있네요. 혼란 방지를 위해 조정이 필요한 부분 아닐까 싶습니다.

2024-08-15 10:28 UTC, DokaDev commented on src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
> +            reviewReportDTO.setReviewDTO(reviewReportService.returnReviewDTO(report.getId()));
해당내용도 상기 내용과 같이 review파트의 서비스단을 주입받으셔서 재사용하셔야 할 듯 합니다.

다만, 현재 dto로 객체를 매핑하여 사용하고 계신데, 저 포함해서 다른 파트 분들께서는 우선은 entity 전달 형태로 로직을 작성하고 계시며 추후에 entity->dto 형태로 전달하도록 조정하려고 합니다. 아직 엔티티 구조의 부분적인 변경이 아직 발생되고 있다 보니 현 시점에서 entity구조가 조정되면 entity도 함께 바뀌어야 하는 번거로움이 있기 때문인 점 양해 부탁드려요

2024-08-15 10:28 UTC, DokaDev commented on src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
> +    public ReviewCommentDTO returnReviewCommentDTO(Long id) {
상기 내용과 동일합니다.

2024-08-15 10:28 UTC, DokaDev commented on src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
> +    public ReviewDTO returnReviewDTO(Long id) {
상기 내용과 동일합니다.

2024-08-17 11:25 UTC, kebin0591 submitted a review, later dismissed
아따 고생하셧슴니다

2024-08-17 11:54 UTC, DokaDev approved these changes

2024-08-18 06:52 UTC, kebin0591 approved these changes

2024-08-18 07:29 UTC, Lucas-Choi-17 approved these changes
확인했습니다!! 고생하셨어요!!

2024-08-18 08:44 UTC, merged