Feat: 회원 가입, 로그인, 로그아웃, 이메일인증 컨트롤러, 서비스
ssg-240304-java2/final-whiskey pull request #185
Opened 2024-08-17 12:20 UTC by speter6501

-devel로 머지 요청합니다.

2024-08-18 06:51 UTC, kebin0591 commented
최신 브랜치하고 병합 테스트 하면서 따로 이슈는 없으셨죠?

2024-08-18 07:16 UTC, speter6501 commented
> 최신 브랜치하고 병합 테스트 하면서 따로 이슈는 없으셨죠?

따로 conflict같은 오류는 없었습니다

2024-08-18 07:34 UTC, Lucas-Choi-17 submitted a review, later dismissed
확인했습니다. 이상 없습니다!!

2024-08-18 09:17 UTC, l2chmnl submitted a review, later dismissed
확인했습니다.

2024-08-18 10:22 UTC, kebin0591 approved these changes

2024-08-19 05:29 UTC, DokaDev commented
금요일 이후 병합검토시작하겠습니다.

2024-08-19 05:29 UTC, DokaDev requested changes
병합 보류할게요.

2024-08-20 02:54 UTC, Lucas-Choi-17 submitted a review, later dismissed
확인했습니다.

2024-08-20 07:02 UTC, Lucas-Choi-17 approved these changes
확인했습니다.

2024-08-20 07:12 UTC, closed without merging