Feat(report) : 식당 신고 전체 조회 웹연동2 #189
ssg-240304-java2/final-whiskey pull request #195
Opened 2024-08-18 10:57 UTC by l2chmnl

- UI/UX 임시로 해놓고 전체 목록 불러오는 기능 완성입니다.
 + detail 구상 중 길을 잃어서 체크포인트 겸 저장용 commit 입니다.

2024-08-18 11:14 UTC, kebin0591 approved these changes
GOODGOOD

2024-08-18 12:02 UTC, DokaDev commented on src/main/resources/templates/adminReport.html
> +        location.href = `/report/${buttonId}Report`;
이거 url요청에 Report라는 문자열 상수가 postfix로 붙어도 괜찮은건가요? 혹시 의도하신 내용이 맞는지 해서 여쭙니다.

2024-08-18 12:37 UTC, l2chmnl commented on src/main/resources/templates/adminReport.html
> +        location.href = `/report/${buttonId}Report`;
넵 의도한 내용입니다!

2024-08-18 14:12 UTC, DokaDev approved these changes

2024-08-18 14:12 UTC, DokaDev commented on src/main/resources/templates/adminReport.html
> +        location.href = `/report/${buttonId}Report`;
확인했습니다. 조금 더 자세하게 여쭙고싶은 내용이 있어서 우선은 승인 후 내일 설명 부탁드리겠습니다.

2024-08-19 00:15 UTC, DokaDev requested changes

2024-08-19 00:15 UTC, DokaDev commented on src/main/java/com/whiskey/rvcom/report/controller/ReportController.java
>      public String getRestaurantReport() {
adminReport에서 정의한 buttonId + report 형식으로 매핑되도록 조정 부탁드립니다.
1. 컨트롤러
2. html쪽 prefix 소문자로 변경
적용부탁드립니다.

2024-08-19 00:41 UTC, zZerorok approved these changes
웹 연동을 하고 계시군요 저도 속도를 더 내겠습니다!!

2024-08-19 05:31 UTC, DokaDev approved these changes

2024-08-19 05:32 UTC, merged